### ISSUE TITLE
Installation Lab

### ISSUE THREAD

**Issue by hanungwidatama** [hanungwidatama/SEBC#2]

**Comment by mfernest** [comment]
Can you say which lab step you are working on right now?

**Comment by hanungwidatama** [comment]
I have been completed setup cloudera manager and running well in CLI,but still can not access from local laptop,i still looking for this problem.
I used google virtual machine.
Thank You

**Comment by mfernest** [comment]
What is the URL for your Cloudera Manager?

**Comment by hanungwidatama** [comment]
Thanks for your support,now my cloudera manager already accessed from internet

**Comment by hanungwidatama** [comment]
![cm all cluster](https://cloud.githubusercontent.com/assets/25724952/22957793/4a73b8aa-f35d-11e6-8a7b-79d2ba688e46.png)

**Comment by hanungwidatama** [comment]
I have one problem before this,my cluster can not accessed by ssh use ssh client with this error "Disconnected: No supported authentication methods available (server sent: publickey)"
Then the fixing is modified /etc/ssh/sshd.config
PasswordAuthentication yes
ChallengeResponseAuthentication yes
